name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t catevika9565/auth .
<<<<<<< HEAD
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
=======
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
>>>>>>> ecc85e5b66213ccb8173ace43e5a358a09a27a1b
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER.USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER.PASSWORD }}
      - run: docker push catevika9565/auth
