name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t catevika9565/auth .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER.USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER.PASSWORD }}
      - run: docker push catevika9565/auth
