name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t catevika9565/tickets .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB.USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB.PASSWORD }}
      - run: docker push catevika9565/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save udemy-microservices-ticketing
      - run: kubectl rollout restart deployment tickets-depl
