name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t catevika9565/auth .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB.USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB.PASSWORD }}
      - run: docker push catevika9565/auth
